### ISSUE TITLE
Weather Map sync update setting

### ISSUE THREAD

**Issue by kristaufel** [CA-PM/device_google_geo_map#2]
Hello everyone, have a question for weather map integration with CAPM 3.5. If we show on dashboard with last hours range, the value on weathermap is 0% like below 

![pastedimage_1](https://user-images.githubusercontent.com/43579114/46022578-18d2bd80-c10d-11e8-8e54-981bc6a6ea73.jpg)

But, if we change to last 2 hours, last 4 hours or more, the value is good like below

![pastedimage_2](https://user-images.githubusercontent.com/43579114/46022653-34d65f00-c10d-11e8-8b88-20ce7707a635.jpg)
Any setting for make sure how long weather map sync query or do something to DA or CAPC dashboard???

**Comment by jasonnormandin** [comment]
I believe the App is set to use hourly resolution data in the query. You can modify those queries and change the ‘resolution’ flag to RATE for as-polled data.

**Comment by kristaufel** [comment]
Modify on CA performance management dashboard or weatherMap source code you mean?

**Comment by irsanrml** [comment]
Hi... @jasonnormandin I'm kristaufel's Team, 

here capture resolution code from index.html 

![image](https://user-images.githubusercontent.com/4324813/46061100-b8389480-c18f-11e8-8a0c-877f13579a9e.png)

what parameters can be filled? default is HOUR.

Thanks

**Comment by jasonnormandin** [comment]
Change resolution parameter value to RATE

On Sep 26, 2018, at 2:29 AM, irsanrml <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This email originated from outside of CA. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi... @jasonnormandin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasonnormandin&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=b9-mNZGjKeTzSfU0XhsdUO6G6jM59yNrO0U-p-1YLqw&m=FwyFJnuOeSw-XuESC0VpwL0Kq0ZpnF5HDVHUgGtyJak&s=NWwGzWqv9sNH3pWWSVF1qY4xgPAilcJukcAoGOFQZNo&e=> I'm kristaufel's Team,

here capture resolution code from index.html

[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4324813_46061100-2Db8389480-2Dc18f-2D11e8-2D8a0c-2D877f13579a9e.png&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=b9-mNZGjKeTzSfU0XhsdUO6G6jM59yNrO0U-p-1YLqw&m=FwyFJnuOeSw-XuESC0VpwL0Kq0ZpnF5HDVHUgGtyJak&s=6qUo7W-PmMaKXr3-rvTEQr9qVkQoYq0H4xO0ylnfU_w&e=>

what parameters can be filled? default is HOUR.

Thanks

**Comment by kristaufel** [comment]
case close, thank you very much
